superadmin config review
automationiberia/controller-casc-cd pull request #3
Opened 2023-04-25 14:39 UTC by charlyif

2023-04-25 15:25 UTC, ivarmu requested changes

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +Initial configuration files must be created. First of all, the connection credentials to the controller are needed. They will be created under the `group_vars` directory as it will differ from one en
Will people deduce that they need to create a file called `inventory` defining the groups/environments used afterwards?

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +cat > group_vars/all/gitlab_vars.yml <<EOF
I'd prefer to maintain the `cat` part to let direct copy/paste.

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +cat > group_vars/dev/vault <<EOF
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +The previous files should be encrypted as they contain sensitive information and is not recommended to store it in plain text. In our case we will use 'ansible-vault'
back-ticks for \`ansible-vault\`?

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +//.Click here if you want to create all the files from scratch (images not included)
remove better than comment out.

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
Collapsible must be followed by delimiters like follows (can have different length):

\========
\========

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-25 15:25 UTC, ivarmu commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
idem

2023-04-26 07:11 UTC, charlyif commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +Initial configuration files must be created. First of all, the connection credentials to the controller are needed. They will be created under the `group_vars` directory as it will differ from one en
I moved the inventory creation a bit earlier (line 68) as a first step before all the directory structure. It felt a bit less obvious the content here to me

2023-04-26 07:14 UTC, charlyif commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +cat > group_vars/all/gitlab_vars.yml <<EOF
I kept them on these ones (just deleted the cat part for later ones that collapse). It might be this view that makes it confusing as it is not allign, if you check the file the 'cat' should be all there.

2023-04-26 07:15 UTC, charlyif commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +The previous files should be encrypted as they contain sensitive information and is not recommended to store it in plain text. In our case we will use 'ansible-vault'
Same as before, I think is just the view allignment

2023-04-26 07:15 UTC, charlyif commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +//.Click here if you want to create all the files from scratch (images not included)
Agree, but I didn't want to delete in case you have it there for later analysis.

2023-04-26 07:16 UTC, charlyif commented on documentation/modules/ROOT/pages/021-initial-dir-and-files.adoc
> +[%collapsible]
Ok. My bad, I didn't review the order of lines for this

2023-05-03 10:32 UTC, merged